### ISSUE TITLE
Make some ggplot complete themes compatible by default

### ISSUE THREAD

**Issue by tvroylandt** [rstudio/thematic#16]
Thanks for this awesome package !

By default, adding some elements on the plot will overlap the `thematic` styling. 

This is a good behaviour, but it could be difficult to handle when you add complete themes (like `theme_minimal`) because they remove part the choices you made with `thematic`.

As show below, some workaround is possible.

```
library(thematic)
library(ggplot2)

thematic_on(
  bg = "#F4F4E2",
  fg = "#4c4c4c",
  accent = "#741336",
  font = font_spec("Special Elite", scale = 0.5),
  qualitative = paletteer::paletteer_d("dutchmasters::milkmaid"),
  sequential = sequential_gradient(0.5, 0.75)
)

# this works fine
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color =  Species)) +
  geom_point()

# this one doesn't works fine
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color =  Species)) +
  geom_point() +
  theme_minimal()

# workaround
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color =  Species)) +
  geom_point() +
  theme_minimal(base_family = thematic_get_option("font")$families,
                base_size = thematic_get_option("font")$scale * 11,
                base_line_size = 1.1)
```

But adding more elements or making a custom `theme` by hand goes against the philosophy of `thematic` to simplify things. Wouldn't it be possible to make some themes compatible with `thematic` by default ? Or make new themes near from the old ones which are compatible ?

Thanks !

**Comment by cpsievert** [comment]
Thanks for bringing this up. The good news is that **thematic** could potentially work better with complete themes *if* you update the global theme *prior to* calling `thematic_on()`

```r
library(ggplot2)
theme_set(theme_minimal())
thematic::thematic_on()
```

That's because, `thematic_on()` just updates global defaults, and right now it does it in such a way as to mimic design decisions specific to `theme_gray()` (the default global theme), but it could do better to update dynamically based on relevant design decisions within the global theme.

The bad news is that I don't think there's a decent way for **thematic** to ever play well with plot-specific code that adds a complete theme (e.g., `p + theme_minimal()`, `p + theme_bw()`, etc) since that complete theme is likely going to override decisions made by `thematic_on()`.

**Comment by tvroylandt** [comment]
Thank you for your quick answer !
